name: Reset Task Completion Daily

on:
  schedule:
    - cron: '0 16 * * *'  # 每天 UTC 16:00，台灣時間凌晨 0 點

jobs:
  reset_tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Reset completed field in tasks.json
      run: |
        jq 'map(.completed = false)' tasks.json > tasks_new.json
        mv tasks_new.json tasks.json

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add tasks.json
        git commit -m "Daily reset task completion status"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
